<?php

$title = 'Edit church';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 <?php
 $form->setAttribute('action', $this->url('church', array('action' => 'edit', 'id' => $this->id)));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id')); 
 ?>
 
 <table>
	 <tr>
		 <td> <?=$form->get('name')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('name')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('description')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('description')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('needs')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('needs')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('donation')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('donation')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('banner')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('banner')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('thumbnail')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('thumbnail')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('location')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('location')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('street')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('street')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('city')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('city')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('state')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('state')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('postal_code')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('postal_code')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('country')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('country')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('latitude')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('latitude')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('longitude')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('longitude')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('contactperson')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('contactperson')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('email')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('email')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('phone')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('phone')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('bankname')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('bankname')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('branchname')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('branchname')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('accountname')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('accountname')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('accountnumber')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('accountnumber')); ?></td>
	 </tr>
	 <tr>
	     <td> <?=$form->get('submit')->getLabel(); ?></td>
		 <td> <?=$this->formElement($form->get('submit')); ?></td>
	 </tr>
 </table>
 <?php
 echo $this->form()->closeTag();

