    <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/helping-hands/jssor.js')
            ->prependFile($this->basePath() . '/js/helping-hands/jssor.slider.js')          
            ->prependFile($this->basePath() . '/js/helping-hands/hh-gallery.js')            
     ; ?>
     <?php echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/css/helping-hands/hh-gallery.css')
     ; ?>
    <!-- Jssor Slider Begin -->
    <!-- You can move inline styles to css file or css block. -->
    <div id="slider1_container" style="position: relative; width: 940px; height: 300px;">
        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 940px; height:300px; overflow: hidden;">
            <!-- Slide -->
            <div>
                <img u="image" src="<?php echo $this->basePath();?>/img/helping-hands/gallery-img/landscape/01.jpg" />
                <div u="caption" t="MCLIP|B" style="position: absolute; top: 250px; left: 0px;
                    width: 600px; height: 50px;">
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        background-color: Black; opacity: 0.5; filter: alpha(opacity=50);">
                    </div>
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        color: White; font-size: 16px; font-weight: bold; line-height: 50px; text-align: center;">
                        Simple Caption Definition1: &lt;div u="caption" t="MCLIP|B" ...&gt;&lt;div/&gt;
                        <a href="http://google.com">Google</a>
                    </div>
                </div>
            </div>
            <!-- Slide -->
            <div>
                <img u="image" src="<?php echo $this->basePath();?>/img/helping-hands/gallery-img/landscape/02.jpg" />
                <div u="caption" t="MCLIP|B" t2="T" style="position: absolute; top: 250px; left: 0px;
                    width: 600px; height: 50px;">
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        background-color: Black; opacity: 0.5; filter: alpha(opacity=50);">
                    </div>
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        color: White; font-size: 16px; font-weight: bold; line-height: 50px; text-align: center;">
                        Define both 't' and 't2': &lt;div u="caption" t="MCLIP|B" t2="T" ...&gt;&lt;div/&gt;
                    </div>
                </div>
            </div>
            <!-- Slide -->
            <div>
                <img u="image" src="<?php echo $this->basePath();?>/img/helping-hands/gallery-img/landscape/03.jpg" />
                <div u="caption" t="NO" t2="MCLIP|B" style="position: absolute; top: 250px; left: 0px;
                    width: 600px; height: 50px;">
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        background-color: Black; opacity: 0.5; filter: alpha(opacity=50);">
                    </div>
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        color: White; font-size: 16px; font-weight: bold; line-height: 50px; text-align: center;">
                        Disable 'Play In': &lt;div u="caption" t="NO" t2="MCLIP|B" ...&gt;&lt;div/&gt;
                    </div>
                </div>
            </div>
            <!-- Slide -->
            <div>
                <img u="image" src="<?php echo $this->basePath();?>/img/helping-hands/gallery-img/landscape/04.jpg" />
                <div u="caption" t="MCLIP|B" t2="NO" style="position: absolute; top: 250px; left: 0px;
                    width: 600px; height: 50px;">
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        background-color: Black; opacity: 0.5; filter: alpha(opacity=50);">
                    </div>
                    <div style="position: absolute; top: 0px; left: 0px; width: 600px; height: 50px;
                        color: White; font-size: 16px; font-weight: bold; line-height: 50px; text-align: center;">
                        Disable 'Play Out': &lt;div u="caption" t="MCLIP|B" t2="NO" ...&gt;&lt;div/&gt;
                    </div>
                </div>
            </div>
            <!-- Slide -->
            <div>
                <img u="image" src="<?php echo $this->basePath();?>/img/helping-hands/gallery-img/landscape/05.jpg" />
                <div u="caption" t="WAVE|L" class=bricon style="position:absolute; top:160px; left: 520px; width:30px; height:30px; background-position: -120px 0px;"></div>
                <div u="caption" t="WAVE|L" d="-1350" class=bricon style="position:absolute; top:160px; left: 470px; width:30px; height:30px; background-position: -90px 0px;"></div>
                <div u="caption" t="WAVE|L" d="-1350" class=bricon style="position:absolute; top:160px; left: 420px; width:30px; height:30px; background-position: -60px 0px;"></div>
                <div u="caption" t="WAVE|L" d="-1350" class=bricon style="position:absolute; top:160px; left: 370px; width:30px; height:30px; background-position: -30px 0px;"></div>
                <div u="caption" t="WAVE|L" d="-1350" class=bricon style="position:absolute; top:160px; left: 320px; width:30px; height:30px; background-position: 0px 0px;"></div>
                
            </div>
        </div>
                
        <!-- Arrow Navigator Skin Begin -->
        <style>
            /* jssor slider arrow navigator skin 03 css */
            /*
            .jssora03l              (normal)
            .jssora03r              (normal)
            .jssora03l:hover        (normal mouseover)
            .jssora03r:hover        (normal mouseover)
            .jssora03ldn            (mousedown)
            .jssora03rdn            (mousedown)
            */
            .jssora03l, .jssora03r, .jssora03ldn, .jssora03rdn
            {
            	position: absolute;
            	cursor: pointer;
            	display: block;
                background: url(../img/helping-hands/gallery-img/a03.png) no-repeat;
                overflow:hidden;
            }
            .jssora03l { background-position: -3px -33px; }
            .jssora03r { background-position: -63px -33px; }
            .jssora03l:hover { background-position: -123px -33px; }
            .jssora03r:hover { background-position: -183px -33px; }
            .jssora03ldn { background-position: -243px -33px; }
            .jssora03rdn { background-position: -303px -33px; }
        </style>
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssora03l" style="width: 55px; height: 55px; top: 123px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssora03r" style="width: 55px; height: 55px; top: 123px; right: 8px">
        </span>
        <!-- Arrow Navigator Skin End -->
        <a style="display: none" href="http://www.jssor.com">image carousel</a>
    </div>
    <!-- Jssor Slider End -->
